config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:passwords] ,controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#guest_sign_in'
    delete 'admin_logout' => 'admin/sessions#destroy', as: :logout_admin_session
  end

  namespace :admin do
    root to: 'homes#top'
    resources :quests, only: [:show, :edit, :create, :edit, :update, :destroy, :new]
    resources :members, only: [:index, :show, :edit, :update] do
      get :permission
      get :rejected
    end
    patch 'admin/exchange_requests/:id' => 'update#exchange_request'
    resources :reviews, only: [:new, :create]
    get    '/relationships/invitation_code', to: "relationships#invitation_code"
    resources :relationships,       only: [:new, :create]
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
    #post 'homes/guest_sign_in', to 'homes#new_guest'
  }
  devise_scope :member do
    post 'member/guest_sign_in', to: 'member/sessions#guest_sign_in'
    delete 'member_logout' => 'member/sessions#destroy', as: :logout_member_session
  end

  scope module: 'member' do
    root to: 'homes#top'
    get '/mypage' => 'homes#mypage'
    get '/about' => 'homes#about'
    get '/exchange_requests' => 'quests#exchange_request'
    post '/exchange_requests' => 'quests#exchange_request_receive'
    get 'quests/histories' => 'quests#histories'
    get 'quests/complete/:id' => 'quests#complete', as: 'quests_complete'
    get 'quests/receive/:id' => 'quests#receive', as: 'quests_receive'
    delete 'giveup/:id' => 'quests#giveup', as: 'quests_giveup'
    resources :quests, only: [:show]
    resources :members, only: [:new, :create, :edit, :show, :update]
    resources :wallets, only: [:show, :update]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :quests
  has_many :exchange_requests
  has_many :wallets
  belongs_to :admin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, authentication_keys: %i[nickname]


  validates :nickname, uniqueness: true, presence: true, length: { maximum: 20 }
#  validates :birthday, presence: true

  before_validation :set_admin_id

  def email_required?
    false
  end
  
  def email_changed?
    false
  end

  def self.guest
    find_or_create_by!(is_guest: true) do |member|
      member.admin_id = Admin.guest.id
      member.password = SecureRandom.urlsafe_base64
      member.nickname = 'ゲスト'
      member.birthday = '2023-01-01'
    end
  end

  private
  
  def set_admin_id
    admin = Admin.find_by(invitation_code: self.admin_invitation_code)
    self.admin_id = admin.id if admin && self.new_record?
  end
end

app/models/quest.rb
class Quest < ApplicationRecord
  has_one :wallet
  belongs_to :admin
  belongs_to :member, optional: true
  has_one_attached :quest_image

  scope :not_draft, -> { where(is_draft: false) }
  scope :is_draft, -> { where(is_draft: true) }

  def get_image(width, height)
    unless quest_image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      quest_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    quest_image.variant(resize_to_fill: [width, height]).processed
  end

  with_options presence: true, on: :publicize do
    validates :name
    validates :level
    validates :price
    validates :introduction
  end
  validates :name, length: { maximum: 14 }, on: :publicize
  validates :introduction, length: { maximum: 80 }, on: :publicize

  enum level: { easy: 0, normal: 1, hard: 2 }
  enum status: { recruitment: 0, close: 1, complete: 2 } # TODO: どこかで齟齬がでたらcomplete = 3になっていないか確認
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  layout 'admin_application'

  def index
    @members = current_admin.members.all

  end

  def show
    @member = Member.find(params[:id])
    @quests = Quest.where(member_id: @member.id).where.not(status: 2)

    histories = Wallet.where(member_id: params[:id]).order(created_at: :desc)
    exchange_requests = ExchangeRequest.where(member_id: params[:id]).order(created_at: :desc)

    @have_gold = histories.sum(:remaining_money).to_i - exchange_requests.where.not(appoval_flag: 2).sum(:request_amount)
  end

  def permission #許可 Ｇはそのまま消費される
    member = Member.find(params[:member_id])
    exchange_request = member.exchange_requests.where(appoval_flag: :applying).order(created_at: :desc).first
    if exchange_request
      exchange_request.appoval_flag = :permission
      if exchange_request.save
      else
      end
    end
    redirect_to admin_members_path
  end

  def rejected #拒否 Ｇは消費されずwalletに戻る
    member = Member.find(params[:member_id])
    exchange_request = member.exchange_requests.where(appoval_flag: :applying).order(created_at: :desc).first
    if exchange_request
      if exchange_request.destroy
      else
      end
    end
    redirect_to admin_members_path
  end
end

app/controllers/admin/quests_controller.rb
class Admin::QuestsController < ApplicationController
  layout 'admin_application'
  def index
    @quests = Quest.published.page(params[:page]).reverse_order
    #Quest.publishedとすることで、投稿されたものだけを取得。(下書きのものを取得しない)
  end

  def show
    @quest = Quest.find(params[:id])
  end

  def new
    @quest = Quest.new
  end

  def create
    @quest = current_admin.quests.new(quest_params)
    #@quest = Quest.new(quest_params)
    # 投稿ボタンを押下した場合
    if params[:post]
      if @quest.save(context: :publicize)
        redirect_to admin_quest_path(@quest), notice: "新規クエストを投稿しました！"
      else
        render :new, alert: "登録できませんでした。お手数ですが、入力内容をご確認のうえ再度お試しください"
      end
    # 下書きボタンを押下した場合
    else
      @quest.is_draft = true
      if @quest.save
        redirect_to admin_quest_path(@quest), notice: "クエストを下書き保存しました！"
      else
        render :new, alert: "登録できませんでした。お手数ですが、入力内容をご確認のうえ再度お試しください"
      end
    end
  end

  def edit
    @quest = Quest.find(params[:id])
    @quests = Quest.all
  end
  

  def update
    @quest = Quest.find(params[:id])
    # ①下書きクエストの更新（公開）の場合
    if params[:publicize_draft]
      # クエスト公開時にバリデーションを実施
      # updateメソッドにはcontextが使用できないため、公開処理にはattributesとsaveメソッドを使用する
      @quest.attributes = quest_params.merge(is_draft: false)
      if @quest.save(context: :publicize)
        redirect_to admin_quest_path(@quest.id), notice: "下書きのクエストを公開しました！"
      else
        @quest.is_draft = true
        render :edit, alert: "クエストを公開できませんでした。お手数ですが、入力内容をご確認のうえ再度お試しください"
      end
    # ②公開済みクエストの更新の場合
    elsif params[:update_post]
      @quest.attributes = quest_params
      if @quest.save(context: :publicize)
        redirect_to admin_quest_path(@quest.id), notice: "クエストを更新しました！"
      else
        render :edit, alert: "クエストを更新できませんでした。お手数ですが、入力内容をご確認のうえ再度お試しください"
      end
    # ③下書きクエストの更新（非公開）の場合
    else
      if @quest.update(quest_params)
        redirect_to admin_quest_path(@quest), notice: "下書きクエストを更新しました！"
      else
        render :edit, alert: "更新できませんでした。お手数ですが、入力内容をご確認のうえ再度お試しください"
      end
    end
  end


  def destroy
    @quest = Quest.find(params[:id])
    @quest.destroy
    redirect_to '/admin'
  end

  private

  def quest_params
    params.require(:quest).permit(
      :member_id,
      :name,
      :introduction,
      :price,
      :is_draft,
      :price,
      :level,
      :time,
      :quest_image
    )
  end
end

app/controllers/member/confirmations_controller.rb
# frozen_string_literal: true

class Member::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/member/homes_controller.rb
class Member::HomesController < ApplicationController
  def top
    if member_signed_in?
      @total_quests = current_member.admin.quests.where(member_id: nil).not_draft
      @quests = @total_quests.page(params[:page]).per(8)
    end
  end

  def mypage
    @quests = Quest.where(member_id: current_member.id).not_draft.where.not(status: 2)
  end


  def about
  end



end

app/controllers/member/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Member::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/member/passwords_controller.rb
# frozen_string_literal: true

class Member::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/member/quests_controller.rb
class Member::QuestsController < ApplicationController
before_action :move_to_signed_in, except: [:show]
before_action :have_gold_sum, only: [:histories, :exchange_request, :exchange_request_receive]

  def show
    @quest = Quest.find(params[:id])
  end

  def receive
    @quest = Quest.find(params[:id])
    @quest.update(status: 1, member_id: current_member.id)
    redirect_to root_path, notice: "がんばってこなそうぜ！"
  end

  def complete
    @quest = Quest.find(params[:id])
    @quest.update(status: 2)
    @wallet = Wallet.find_or_create_by(member_id: current_member.id, quest_id: @quest.id) do |q|
      q.remaining_money = @quest.price
    end
  end

  def giveup
    #受注したクエストのmember idをnilにする
    quest = Quest.find(params[:id])
    quest.update(:member_id => nil)
    redirect_to mypage_path
  end

  def histories; end

  def exchange_request
    @exchange_request = ExchangeRequest.new
  end

  def exchange_request_receive
    @exchange_request = ExchangeRequest.new(exchange_request_params)
    if exchange_request_params[:request_amount].to_i <= @have_gold.to_i && @exchange_request.save
      redirect_to root_path, notice: 'どうなるかな？結果をまちましょう！'
    else
      render :exchange_request
    end
  end

  private
  def move_to_signed_in
    unless member_signed_in?
      #サインインしていないメンバーはログインページが表示される
      redirect_to  new_member_session_path
    end
  end


  def exchange_request_params
    params.require(:exchange_request).permit(:request_amount).merge(member_id: current_member.id)
  end

  def have_gold_sum
    @histories = Wallet.where(member_id: current_member.id).order(created_at: :desc)
    @exchange_requests = ExchangeRequest.where(member_id: current_member.id).order(created_at: :desc)

    @have_gold = @histories.sum(:remaining_money).to_i - @exchange_requests.where.not(appoval_flag: 2).sum(:request_amount)
  end

end

app/controllers/member/registrations_controller.rb
# frozen_string_literal: true

class Member::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    #byebug
    #@admin = Admin.find_by(invitation_code: params[:invitation_code])
    #member = Member.find_or_create_by!(nickname: params[:member][:nickname], admin: @admin) do |member|
    #   member.password = SecureRandom.urlsafe_base64
    #   #member.email = SecureRandom.urlsafe_base64+"@example.com"
    #   member.birthday = "#{params[:member]['birthday(1i)']}/#{params[:member]['birthday(2i)']}/#{params[:member]['birthday(3i)']}"
    # end
    # sign_in member
    # redirect_to root_path
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    #binding.pry
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday, :admin_invitation_code])
  end

#  def configure_permitted_parameters
#    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday])
#  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/member/sessions_controller.rb
# frozen_string_literal: true

class Member::SessionsController < Devise::SessionsController
  #before_action :configure_permitted_parameters, if: :devise_controller?

#  protected

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def guest_sign_in
    member = Member.guest
    sign_in member
    redirect_to root_path, notice: 'ゲストメンバーとしてログインしました。'
  end

  def create
    birth_day = "#{params[:member]['birthday(1i)']}/#{params[:member]['birthday(2i)']}/#{params[:member]['birthday(3i)']}"
    member = Member.find_by(nickname: params[:member][:nickname], birthday: birth_day)
    if member != nil
      sign_in member
      redirect_to root_path
    else
      redirect_to new_member_session_path, alert: "なまえかたんじょうびが、まちがっています"
    end
  #   super
  end

  #

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/member/unlocks_controller.rb
# frozen_string_literal: true

class Member::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/quests_helper.rb
module Admin::QuestsHelper
end

app/helpers/member/homes_helper.rb
module Member::HomesHelper
end

app/helpers/member/quests_helper.rb
module Member::QuestsHelper
end

app/views/member/quests/_receive.html.erb
<div class="container mt-5" >
  <%= form_with model: @quest, url: quest_path, method: :post, local: true do |f| %>
   <%= image_tag @quest.get_image(300,300), fallback: "noimage.jpg" %>
   <%= f.hidden_field :member_id, value: current_memgber.id %>
   <%= f.hidden_field :name, value: @quest.name %>
   <%= f.hidden_field :level, value: @quest.level_i18n %>
   <%= f.hidden_field :price, value: @quest.price %>
   <%= f.hidden_field :time, value: @quest.time %>
   <%= f.hidden_field :introduction, value: @quest.introducution %>
   <p>クエストがおわったらチェックしてもらってね！</p>
   <%= f.submit "クエストかんりょう", class: "btn btn-success" %>
  <% end %>
</div>

app/views/member/quests/complete.html.erb
<div class="container mt-5">
  <div class="text-center my-3">
    <h1><strong><span style='color: #FF0F77;'>C</span><span style='color: #FFDE05;'>o</span><span style='color: #93E01F;'>n</span><span style='color: #19A3FE;'>g</span><span style='color: #901DF5;'>r</span><span style='color: #FF0F77;'>a</span><span style='color: #FFDE05;'>t</span><span style='color: #93E01F;'>u</span><span style='color: #19A3FE;'>l</span><span style='color: #901DF5;'>a</span><span style='color: #FF0F77;'>t</span><span style='color: #FFDE05;'>i</span><span style='color: #93E01F;'>o</span><span style='color: #19A3FE;'>n</span><span style='color: #901DF5;'>s</span><span style='color: #FF0F77;'>!!!</span></strong></h1>
    <h3>Quest Complete! Please try the next quest!!</h3>
  </div>
  <div class="text-center">
      <%= image_tag "億万長者.png", alt: "complete-image", :size => '600x600' %>
   </div>
</div>

app/views/member/quests/exchange_request.html.erb
<div class="container">
  <h2 class="text-center my-5">
    <i class="fa-solid fa-coins"></i><i class="fa-solid fa-rotate-left"></i> Exchange Request
  </h2>

  <div class="row">
    <div class="col-md-6 mx-auto">
      <h5>You have Gold:  <strong><%= @have_gold %> G</strong></h5>
      <%= form_with model: @exchange_request, url: exchange_requests_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :request_amount %>
          <%= f.number_field :request_amount, min: 0, max: @have_gold, value: 0, class: 'form-control form-control-lg' %>
        </div>

        <div class="form-group">
          <%= f.submit "G → ¥ 換金しまーす", name: 'post', class: 'mr-5 btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/member/quests/histories.html.erb
<div class="container">
  <h2 class="my-5"><i class="fa-solid fa-wallet"></i> Total Wallets</h2>
  <h1 class="ml-5"><%= @have_gold %> G</h1>

  <div class="row">
    <div class="col-md-6">
      <h2 class="my-5"><i class="fa-solid fa-hands-clapping"></i> Complete Missions!</h2>
      <% @histories.each do |history| %>
        <div>
          <%= link_to history.quest.name, quest_path(history.quest) %>
          <small class="text-black-50">(<%= history.created_at.strftime('%Y年%m月%d日') %>)</small>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <h2 class="my-5"><i class="fa-solid fa-coins"></i><i class="fa-solid fa-rotate-left"></i> ExchangeRequest</h2>
      <% @exchange_requests.each do |exchange_request| %>
        <div>
          <%= exchange_request.request_amount * -1 %>
          <small class="text-black-50">
            <%= exchange_request.appoval_flag_i18n %>
            (<%= exchange_request.created_at.strftime('%Y年%m月%d日') %>)
          </small>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/member/quests/receive.html.erb
<div class="container mt-5" >
  <%= form_with model: @quest, url: quest_path, method: :post, local: true do |f| %>
   <%= image_tag @quest.get_image(300,300), fallback: "noimage.jpg" %>
   <%= f.hidden_field :member_id, value: current_memgber.id %>
   <%= f.hidden_field :name, value: @quest.name %>
   <%= f.hidden_field :level, value: @quest.level_i18n %>
   <%= f.hidden_field :price, value: @quest.price %>
   <%= f.hidden_field :time, value: @quest.time %>
   <%= f.hidden_field :introduction, value: @quest.introducution %>
   <p>クエストがおわったらチェックしてもらってね！</p>
   <%= f.submit "クエストかんりょう", class: "btn btn-success" %>
  <% end %>
</div>

app/views/member/quests/show.html.erb
<div class="container text-center my-5">
 <%= image_tag @quest.get_image(300,300), fallback: "noimage.jpg" %>
 <h3><%= @quest.name %></h3>
 <p>Level : <%= @quest.level_i18n %></p>
 <p>Reward : <%= @quest.price.to_i.to_s(:delimited, delimiter: ',') %>Ｇ</p>
 <p>Time : <%= @quest.time %>分</p>
 <p><%= simple_format(@quest.introduction) %></p>
 <%= link_to "このクエストにする", quests_receive_path(@quest), class: "btn btn-primary" unless @quest.status == 'complete' %>
 <%= link_to "最初のページにもどる", root_path, class: "btn btn-secondary" %>
</div>