config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:passwords] ,controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#guest_sign_in'
    delete 'admin_logout' => 'admin/sessions#destroy', as: :logout_admin_session
  end

  namespace :admin do
    root to: 'homes#top'
    resources :quests, only: [:show, :edit, :create, :edit, :update, :destroy, :new]
    resources :members, only: [:index, :show, :edit, :update] do
      get :permission
      get :rejected
    end
    patch 'admin/exchange_requests/:id' => 'update#exchange_request'
    resources :reviews, only: [:new, :create]
    get    '/relationships/invitation_code', to: "relationships#invitation_code"
    resources :relationships,       only: [:new, :create]
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
    #post 'homes/guest_sign_in', to 'homes#new_guest'
  }
  devise_scope :member do
    post 'member/guest_sign_in', to: 'member/sessions#guest_sign_in'
    delete 'member_logout' => 'member/sessions#destroy', as: :logout_member_session
  end

  scope module: 'member' do
    root to: 'homes#top'
    get '/mypage' => 'homes#mypage'
    get '/about' => 'homes#about'
    get '/exchange_requests' => 'quests#exchange_request'
    post '/exchange_requests' => 'quests#exchange_request_receive'
    get 'quests/histories' => 'quests#histories'
    get 'quests/complete/:id' => 'quests#complete', as: 'quests_complete'
    get 'quests/receive/:id' => 'quests#receive', as: 'quests_receive'
    delete 'giveup/:id' => 'quests#giveup', as: 'quests_giveup'
    resources :quests, only: [:show]
    resources :members, only: [:new, :create, :edit, :show, :update]
    resources :wallets, only: [:show, :update]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :quests
  has_many :exchange_requests
  has_many :wallets
  belongs_to :admin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, authentication_keys: %i[nickname]


  validates :nickname, uniqueness: true, presence: true, length: { maximum: 20 }
#  validates :birthday, presence: true

  before_validation :set_admin_id

  def email_required?
    false
  end
  
  def email_changed?
    false
  end

  def self.guest
    find_or_create_by!(is_guest: true) do |member|
      member.admin_id = Admin.guest.id
      member.password = SecureRandom.urlsafe_base64
      member.nickname = 'ゲスト'
      member.birthday = '2023-01-01'
    end
  end

  private
  
  def set_admin_id
    admin = Admin.find_by(invitation_code: self.admin_invitation_code)
    self.admin_id = admin.id if admin && self.new_record?
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  layout 'admin_application'
  def top
    if admin_signed_in?
    @total_quests = current_admin.quests.where.not(status: 2)
    @quests = @total_quests.page(params[:page]).per(10)
    else
    # ログインしていない場合の処理を追加（例：エラーメッセージやリダイレクト処理など）
    flash[:notice] = 'ログインが必要です'
    redirect_to new_admin_session_path
    end
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  layout 'admin_application'

  def index
    @members = current_admin.members.all

  end

  def show
    @member = Member.find(params[:id])
    @quests = Quest.where(member_id: @member.id).where.not(status: 2)

    histories = Wallet.where(member_id: params[:id]).order(created_at: :desc)
    exchange_requests = ExchangeRequest.where(member_id: params[:id]).order(created_at: :desc)

    @have_gold = histories.sum(:remaining_money).to_i - exchange_requests.where.not(appoval_flag: 2).sum(:request_amount)
  end

  def permission #許可 Ｇはそのまま消費される
    member = Member.find(params[:member_id])
    exchange_request = member.exchange_requests.where(appoval_flag: :applying).order(created_at: :desc).first
    if exchange_request
      exchange_request.appoval_flag = :permission
      if exchange_request.save
      else
      end
    end
    redirect_to admin_members_path
  end

  def rejected #拒否 Ｇは消費されずwalletに戻る
    member = Member.find(params[:member_id])
    exchange_request = member.exchange_requests.where(appoval_flag: :applying).order(created_at: :desc).first
    if exchange_request
      if exchange_request.destroy
      else
      end
    end
    redirect_to admin_members_path
  end
end

app/controllers/member/confirmations_controller.rb
# frozen_string_literal: true

class Member::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/member/homes_controller.rb
class Member::HomesController < ApplicationController
  def top
    if member_signed_in?
      @total_quests = current_member.admin.quests.where(member_id: nil).not_draft
      @quests = @total_quests.page(params[:page]).per(8)
    end
  end

  def mypage
    @quests = Quest.where(member_id: current_member.id).not_draft.where.not(status: 2)
  end


  def about
  end



end

app/controllers/member/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Member::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/member/passwords_controller.rb
# frozen_string_literal: true

class Member::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/member/quests_controller.rb
class Member::QuestsController < ApplicationController
before_action :move_to_signed_in, except: [:show]
before_action :have_gold_sum, only: [:histories, :exchange_request, :exchange_request_receive]

  def show
    @quest = Quest.find(params[:id])
  end

  def receive
    @quest = Quest.find(params[:id])
    @quest.update(status: 1, member_id: current_member.id)
    redirect_to root_path, notice: "がんばってこなそうぜ！"
  end

  def complete
    @quest = Quest.find(params[:id])
    @quest.update(status: 2)
    @wallet = Wallet.find_or_create_by(member_id: current_member.id, quest_id: @quest.id) do |q|
      q.remaining_money = @quest.price
    end
  end

  def giveup
    #受注したクエストのmember idをnilにする
    quest = Quest.find(params[:id])
    quest.update(:member_id => nil)
    redirect_to mypage_path
  end

  def histories; end

  def exchange_request
    @exchange_request = ExchangeRequest.new
  end

  def exchange_request_receive
    @exchange_request = ExchangeRequest.new(exchange_request_params)
    if exchange_request_params[:request_amount].to_i <= @have_gold.to_i && @exchange_request.save
      redirect_to root_path, notice: 'どうなるかな？結果をまちましょう！'
    else
      render :exchange_request
    end
  end

  private
  def move_to_signed_in
    unless member_signed_in?
      #サインインしていないメンバーはログインページが表示される
      redirect_to  new_member_session_path
    end
  end


  def exchange_request_params
    params.require(:exchange_request).permit(:request_amount).merge(member_id: current_member.id)
  end

  def have_gold_sum
    @histories = Wallet.where(member_id: current_member.id).order(created_at: :desc)
    @exchange_requests = ExchangeRequest.where(member_id: current_member.id).order(created_at: :desc)

    @have_gold = @histories.sum(:remaining_money).to_i - @exchange_requests.where.not(appoval_flag: 2).sum(:request_amount)
  end

end

app/controllers/member/registrations_controller.rb
# frozen_string_literal: true

class Member::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    #byebug
    #@admin = Admin.find_by(invitation_code: params[:invitation_code])
    #member = Member.find_or_create_by!(nickname: params[:member][:nickname], admin: @admin) do |member|
    #   member.password = SecureRandom.urlsafe_base64
    #   #member.email = SecureRandom.urlsafe_base64+"@example.com"
    #   member.birthday = "#{params[:member]['birthday(1i)']}/#{params[:member]['birthday(2i)']}/#{params[:member]['birthday(3i)']}"
    # end
    # sign_in member
    # redirect_to root_path
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    #binding.pry
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday, :admin_invitation_code])
  end

#  def configure_permitted_parameters
#    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday])
#  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/member/sessions_controller.rb
# frozen_string_literal: true

class Member::SessionsController < Devise::SessionsController
  #before_action :configure_permitted_parameters, if: :devise_controller?

#  protected

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def guest_sign_in
    member = Member.guest
    sign_in member
    redirect_to root_path, notice: 'ゲストメンバーとしてログインしました。'
  end

  def create
    birth_day = "#{params[:member]['birthday(1i)']}/#{params[:member]['birthday(2i)']}/#{params[:member]['birthday(3i)']}"
    member = Member.find_by(nickname: params[:member][:nickname], birthday: birth_day)
    if member != nil
      sign_in member
      redirect_to root_path
    else
      redirect_to new_member_session_path, alert: "なまえかたんじょうびが、まちがっています"
    end
  #   super
  end

  #

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/member/unlocks_controller.rb
# frozen_string_literal: true

class Member::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/member/homes_helper.rb
module Member::HomesHelper
end

app/helpers/member/quests_helper.rb
module Member::QuestsHelper
end

app/views/member/homes/_top_for_login.html.erb
<div class="container text-center my-5">
  <div class="row">
    <div class="col-md-10">
      <h1><strong><span style= 'color: #2C7CFF;'>H</span><span style= 'color: #7B3CFF;'>e</span><span style= 'color: #FF1A6F;'>l</span><span style='color: #FF570D;'>p</span>
      <span style='color: #BEFF15;'>W</span><span style='color: #13EEFF;'>a</span><span style='color: #2C7CFF;'>n</span><span style='color: #7B3CFF;'>t</span><span style='color: #FF1A6F;'>e</span><span style='color: #FF570D;'>d</span><span style='color: #FF1A6F;'>!!</span></strong></h1>
      <p class="mb-5"><strong>～Let's start the quest～</strong></p>
      <h3><i class="fa-solid fa-list"></i> Quests list</h3><h5>(全<%= @total_quests.count %>件)</h5>
        <div class="row">
          <% @quests.each do |quest| %>
          <div class="col-md-3 mt-5">
            <%= link_to quest_path(quest), class: "link" do %>


            <div class="card border-warning text-white bg-warning mb-3">
              <div class="card-header border-light  text-center"><strong><%= quest.name %></strong></div>
            <%= image_tag quest.get_image(250,250), fallback: "noimage.jpg", class: "card-img-top" %>
              <div class="card-footer border-light">
              <p class="card-text text-center">Level: <%= quest.level_i18n %></p>
              <p class="card-text text-center">Reward: <%= quest.price.to_i.to_s(:delimited, delimiter: ',') %> G</p>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
        </div>
    </div>
  </div>
  <%= paginate @quests, theme: 'bootstrap-5' %>
</div>

app/views/member/homes/_top_for_logout.html.erb
<div class="container">
  <div class="container mt-5">
    <div class="text-center">
      <h1 class="title mt-3"><strong><span style= 'color: #2C7CFF;'>H</span><span style= 'color: #7B3CFF;'>e</span><span style= 'color: #FF1A6F;'>l</span><span style='color: #FF570D;'>p</span><span style='color: #BEFF15;'>W</span><span style='color: #13EEFF;'>a</span><span style='color: #2C7CFF;'>n</span><span style='color: #7B3CFF;'>t</span><span style='color: #FF1A6F;'>e</span><span style='color: #FF570D;'>d</span><span style='color: #FF1A6F;'>!!</span></strong></h1>
      <p class="mb-5"><strong>～Let's start the quest～</strong></p>
      <h3 class="subtitle my-5"><strong><span style= 'color: #2C7CFF;'>H</span><span style= 'color: #7B3CFF;'>e</span><span style= 'color: #FF1A6F;'>l</span><span style='color: #FF570D;'>p</span><span style='color: #BEFF15;'>W</span><span style='color: #13EEFF;'>a</span><span style='color: #2C7CFF;'>n</span><span style='color: #7B3CFF;'>t</span><span style='color: #FF1A6F;'>e</span><span style='color: #FF570D;'>d</span><span style='color: #FF1A6F;'>!!</span></strong> ではクエストに挑戦してくれる人を大募集中！！<br>
      お手伝いクエストに挑戦して<span style='color: gold;'><strong>Gold</strong></span>を<span style='color: red;'><strong>GET</strong></span>しようぜ！</h3>
    </div>
  </div>
   <div class="text-center">
      <%= image_tag "quest.png", alt: "quest-image", :size => '500x500' %>
   </div>
</div>  

app/views/member/homes/about.html.erb
<%= render "member/homes/top_for_logout" %>

<div class="container">
  <div class="container mt-2">
    <div class="text-center">
      <p>家庭内通貨<span style='color: gold;'><strong>【G -ゴールド-】</strong></span>を使用したお手伝いサイトです。投稿されたクエストをクリアすることにより、<span style='color: gold;'><strong>【G】</strong></span>が<br>
      報酬として付与されます。この<span style='color: gold;'><strong>【G】</strong></span>は現金へ換金することができます。ログイン後、右上の <span style= 'color: #FF1A6F;'>Exchange Request</span> <br>
      から換金したい金額を入力して換金のお願いをしましょう!!　※ご利用は計画的に。</p>
    </div>
  </div>
</div>

app/views/member/homes/mypage.html.erb
<div class="container mt-5">
 <div class="text-center">
  <h2 class= "my-3">Quests</h2>
  <% if @quests.count > 0 %>
    <div class="row">
      <% @quests.each do |quest| %>
        <div class="col-md-4">
          <div class="card">
            <%= image_tag quest.get_image(250,250), fallback: "noimage.jpg", class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">
                <%= quest.name %>
              </h5>
              <div class="card-text">
                <div>
                  <%= quest.level_i18n %>
                </div>
                <div>
                  <%= quest.price.to_i.to_s(:delimited, delimiter: ',') %>Ｇ
                </div>
              </div>
            </div>
            <div class="card-footer text-center">
              <%= link_to 'Complete!', quests_complete_path(quest), class: 'btn btn-primary' %>
              <%= link_to 'Give up…', quests_giveup_path(quest), method: :delete, data: {confirm: "え？ほんとにやめるの？"}, class:'text-danger btn btn-secondary' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h4>Nothing... <i class="fa-regular fa-face-sad-tear"></i></h4>
  <% end %>
 </div>

  <div class="row">
    <div class="col">
      <h3 class="my-5"><i class="fa-solid fa-child-reaching"></i>  <%= current_member.nickname %>'s Member details  <i class="fa-solid fa-child-reaching"></i></h3>
        <div class="d-flex align-items-center">
          <table class="table table-borderless">
            <tr>
              <th class="text-center">Member ID</td>
              <td><%= current_member.id %></td>
            </tr>
            <tr>
              <th class="text-center">Nickname</th>
              <td><%= current_member.nickname %></td>
            </tr>
            <tr>
              <th class="text-center">Birthday</th>
              <td><%= current_member.birthday %></td>
            </tr>
            <tr>
              <td>
                <%#= link_to "Edit", edit_admin_member_path, class:"btn btn-success" %>
                <%#= link_to "Back", admin_members_path, class:"btn btn-primary" %>
              </td>
            </tr>

          </table>
      </div>
    </div>
  </div>
</div>

app/views/member/homes/top.html.erb
<% if current_member %>
  <%= render "member/homes/top_for_login" %>
<% else %>
  <%= render "member/homes/top_for_logout" %>
<% end %>