config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:passwords] ,controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#guest_sign_in'
    delete 'admin_logout' => 'admin/sessions#destroy', as: :logout_admin_session
  end

  namespace :admin do
    root to: 'homes#top'
    resources :quests, only: [:show, :edit, :create, :edit, :update, :destroy, :new]
    resources :members, only: [:index, :show, :edit, :update] do
      get :permission
      get :rejected
    end
    patch 'admin/exchange_requests/:id' => 'update#exchange_request'
    resources :reviews, only: [:new, :create]
    get    '/relationships/invitation_code', to: "relationships#invitation_code"
    resources :relationships,       only: [:new, :create]
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
    #post 'homes/guest_sign_in', to 'homes#new_guest'
  }
  devise_scope :member do
    post 'member/guest_sign_in', to: 'member/sessions#guest_sign_in'
    delete 'member_logout' => 'member/sessions#destroy', as: :logout_member_session
  end

  scope module: 'member' do
    root to: 'homes#top'
    get '/mypage' => 'homes#mypage'
    get '/about' => 'homes#about'
    get '/exchange_requests' => 'quests#exchange_request'
    post '/exchange_requests' => 'quests#exchange_request_receive'
    get 'quests/histories' => 'quests#histories'
    get 'quests/complete/:id' => 'quests#complete', as: 'quests_complete'
    get 'quests/receive/:id' => 'quests#receive', as: 'quests_receive'
    delete 'giveup/:id' => 'quests#giveup', as: 'quests_giveup'
    resources :quests, only: [:show]
    resources :members, only: [:new, :create, :edit, :show, :update]
    resources :wallets, only: [:show, :update]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpWanted</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0d2b76896b.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family='Itim', cursive, sans-serif" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <% if admin_signed_in? %>
          <%= link_to "HelpWanted!!", admin_root_path, class:"header-title navber-brand", :style=>"color:white; text-decoration:none;" %>
          <% else %>
          <%= link_to "HelpWanted!!", root_path, class: "header-title navbar-brand", :style=>"color:white; text-decoration:none;" %>
        <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <% if admin_signed_in? %>
              <li class="nav-item-activ mr-5">
                  <span class="nav-link text-dark"><strong>Administrator screen</strong></span>
                  <span class="nav-link text-dark"><strong>Invitation code:<%= current_admin.invitation_code %></strong></span>
              </li>
                <li class="nav-item mr-2">
                  <%= link_to admin_members_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-users"></i>
                      Members list
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to admin_root_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-list"></i>
                      Quests list
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to logout_admin_session_path, method: :delete, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-right-from-bracket"></i>
                      Log out
                  <% end %>
                </li>

              <% else %>
                <li class="nav-item">
                  <%= link_to new_admin_session_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-sign-in-alt"></i>
                      Log in
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to new_admin_registration_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-user-plus"></i>
                      Sign up
                  <% end %>
                </li>
                
                <li class="nav-item mr-2">
                  <%= link_to new_member_session_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-sign-in-alt"></i>
                     Member Log in
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to  admin_guest_sign_in_path, class: 'nav-link text-black', method: :post do %>
                    <i class="fa-solid fa-person-circle-question"></i>
                      Guest Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>

      </nav>
  </header>
  <% if notice %>
    <div class="alert alert-warning">
      <%= notice %>
    </div>
  <% end %>

   <%# flash.each do |message_type, message| %>
      <%#= message %>
    <%# end %>
    <%= yield %>
    <% if Rails.env.development? %>
      <div>admin: <%= current_admin.inspect %></div>
      <div>member: <%= current_member.inspect %></div>
    <% end %>
  <footer class="bg-info">
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p></p>
        </div>
      </div>
    </div>
  </footer>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpWanted</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0d2b76896b.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family='Itim', cursive, sans-serif" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <% if admin_signed_in? %>
          <%= link_to "HelpWanted!!", admin_root_path, class:"header-title navber-brand", :style=>"color:white; text-decoration:none;" %>
        <% else %>
          <%= link_to "HelpWanted!!", root_path, class: "header-title navbar-brand", :style=>"color:white; text-decoration:none;" %>
        <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <% if member_signed_in? %>
                <li class="nav-item-activ mr-5">
                  <span class="nav-link text-dark"><strong>Logging in  <%= current_member.nickname %></strong></span>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to mypage_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-user"></i>
                      My page
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to quests_histories_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-clock-rotate-left"></i>
                      Histories
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to exchange_requests_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-coins"></i><i class="fa-solid fa-rotate-left"></i>
                      Exchange Requests
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to root_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-list"></i>
                      Quests list
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to logout_member_session_path, method: :delete, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-right-from-bracket"></i>
                      Log out
                  <% end %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item mr-2">
                  <%= link_to admin_members_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-users"></i>
                      Members list
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to admin_root_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-list"></i>
                      Quests list
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-right-from-bracket"></i>
                      Log out
                  <% end %>
                </li>

              <% elsif %>
                <li class="nav-item mr-2">
                  <%= link_to about_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-link"></i>
                      About
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to new_member_registration_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-user-plus"></i>
                      Sign up
                  <% end %>
                </li>

                <li class="nav-item mr-2">
                  <%= link_to new_member_session_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-sign-in-alt"></i>
                      Log in
                  <% end %>
                </li>
                
                <li class="nav-item mr-2">
                  <%= link_to new_admin_session_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-sign-in-alt"></i>
                      Admin Log in
                  <% end %>
                </li>
                
                <li class="nav-item mr-2">
                  <%= link_to  member_guest_sign_in_path, class: 'nav-link text-black', method: :post do %>
                    <i class="fa-solid fa-person-circle-question"></i>
                      Guest Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>

      </nav>
  </header>
  <% if notice %>
    <div class="alert alert-warning">
      <%= notice %>
    </div>
  <% end %>

  <%# flash.each do |message_type, message| %>
    <%#= message %>
  <%# end %>

  <%= yield %>
  <% if Rails.env.development? %>
    <div>admin: <%= current_admin.inspect %></div>
    <div>member: <%= current_member.inspect %></div>
  <% end %>
  <footer class="bg-info">
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p></p>
        </div>
      </div>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>